function createfigure(figure1, X1, Y1)
%CREATEFIGURE(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 29-Jun-2011 07:35:33


% Create axes
axes('Parent',figure1);
% Uncomment the following line to preserve the X-limits of the axes
% xlim([0 0.6]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim([0 0.05]);
box('on');
hold('all');

% Create plot
plot(X1,Y1,'Color',[0 0 1]);

% Create xlabel
xlabel('Time (s)','FontSize',20);

% Create ylabel
ylabel('Max Fibre Height (cm)','FontSize',20);

% Create arrow
annotation(figure1,'arrow',[0.3482 0.3518],[0.3276 0.1643]);

% Create textbox
annotation(figure1,'textbox','String',{'H_1'},'FontSize',20,...
    'FontName','Arial',...
    'FitHeightToText','off',...
    'LineStyle','none',...
    'Position',[0.3189 0.3071 0.06507 0.1048]);

% Create textarrow
annotation(figure1,'textarrow',[0.3482 0.3464],[0.3919 0.5786],...
    'TextEdgeColor','none',...
    'TextLineWidth',0.5);

% Create textbox
annotation(figure1,'textbox','String',{'H_2'},'FontSize',20,...
    'FontName','Arial',...
    'FitHeightToText','off',...
    'LineStyle','none',...
    'Position',[0.5046 0.2357 0.04543 0.07143]);

% Create arrow
annotation(figure1,'arrow',[0.5321 0.5357],[0.2276 0.1571]);

% Create doublearrow
annotation(figure1,'doublearrow',[0.35 0.5304],[0.6228 0.6238]);

% Create textbox
annotation(figure1,'textbox','String',{'\pi/Im(\lambda)'},'FontSize',20,...
    'FontName','Arial',...
    'FitHeightToText','off',...
    'LineStyle','none',...
    'Position',[0.3546 0.6667 0.1365 0.0881]);

% Create arrow
annotation(figure1,'arrow',[0.5321 0.5304],[0.28 0.3762]);